### ISSUE TITLE
Can't download the release artifact 2.5.1

### ISSUE THREAD

**Issue by albarralnunez** [webofmars/asdf-plugin-scaleway-cli#2]
**Describe the bug**

Getting following error when installing versions 2.5.1
```
asdf-scaleway-cli: Could not download https://github.com/scaleway/scaleway-cli/releases/download/v2.5.1/scw-2-5-1-darwin-arm64
 or https://github.com/scaleway/scaleway-cli/releases/download/v2.5.1/scw-2.5.1-darwin-arm64
```
**Steps to reproduce**

Run:
```bash
asdf install scaleway-cli 2.5.1
```

**Additional context**
The problem is a change in the naming convention of the artifact name for version 2.5.1.

<img width="902" alt="Screenshot 2022-04-22 at 17 20 54" src="https://user-images.githubusercontent.com/3451448/164837790-d92f6580-2b02-46af-8648-43552f12d0e5.png">

Urls beign tried to download: 
https://github.com/scaleway/scaleway-cli/releases/download/v2.5.1/scw-2-5-1-darwin-arm64 or https://github.com/scaleway/scaleway-cli/releases/download/v2.5.1/scw-2.5.1-darwin-arm64
New format:
https://github.com/scaleway/scaleway-cli/releases/download/v2.5.1/scaleway-cli_2.5.1_darwin_arm64

**Comment by fredleger** [comment]
Fixed by #3
